name: Node.js CI

on: 
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: packageのインストール
        run: yarn 
      - name: ビルド
        run: yarn build 